# Generated by Django 5.1.6 on 2025-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=200)),
                ('dialogue', models.TextField()),
            ],
        ),
    ]
